name: wheels

env:
    CIBW_SKIP: cp2* pp*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

    build_sdist:
        name: Build source distribution
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-python@v2
            name: Install Python
            with:
            python-version: '3.7'

        - name: Build sdist
            run: python setup.py sdist
