name: genieclust for Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt -y install python3-rpy2 libmlpack-dev r-cran-devtools python3-dev
        sudo Rscript -e "install.packages(c('genie', 'Rcpp', 'devtools', 'testthat', 'emstreeR'))"
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt --upgrade; fi
        pip install flake8 pytest --upgrade
        pip install sphinx numpydoc sphinx_rtd_theme sphinx-bootstrap-theme sphinxcontrib-jsmath --upgrade
        pip install rpy2 mlpack nmslib  ipython jupyter tabulate --upgrade
    - name: Test and check Python
      run: |
        make py-test
        make py-check
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  --exclude=devel,build,docs,.git,R,dist,genieclust.egg-info,man,tutorials
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  --exclude=devel,build,docs,.git,R,dist,genieclust.egg-info,man,tutorials
