name: codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install required dependencies
      run: |
        pip install pip wheel cython --upgrade
        pip install -r requirements.txt --upgrade
        pip install pytest pytest-cov --upgrade
    - name: Install optional dependencies
      continue-on-error: true
      run: |
        pip install nmslib --upgrade
        pip install mlpack --upgrade
    - name: Install genieclust
      run: |
        python setup.py install --user
    - name: Generate coverage report
      run: |
        pytest --cov --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        files: ./coverage1.xml,./coverage2.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.gz
